project:
  type: book
  output-dir: docs

number-depth: 2

book:
  title: "STAT 253 Course Notes"
  subtitle: "Fall 2024"
  repo-url: https://github.com/kegrinde/stat253_coursenotes
  repo-actions: [issue, source]  
  page-footer:
    left: |
      Copyright Kelsey Grinde, released under Creative Commons Attribution-ShareAlike 4.0.
  sidebar: 
    collapse-level: 2
  page-navigation: true
  chapters:
    - index.qmd
    - L01.qmd
    - part: "Regression: Model Evaluation"
      chapters:
        - L02.qmd
        - L03.qmd
        - L04.qmd
    - part: "Regression: Building Models"
      chapters:
        - L05.qmd
        - L06.qmd
  appendices:
    - Lab01-R.Rmd
    - Lab02-Python.ipynb
    - DGBecker_QuorseNotes.qmd

format:
  html:
    theme:
      light: [sandstone, smaller_lists.scss]
      dark: [superhero, smaller_lists.scss]
    mainfont: ubuntu, sans-serif
    execute:
      echo: true
      code-fold: true
