project:
  type: book
  output-dir: docs
  resources: 
    - "data/*"
    - "template_qmds/*"

number-depth: 2

book:
  title: "STAT 253: Statistical Machine Learning"
  subtitle: "Fall 2024 Course Notes"
  repo-url: https://github.com/kegrinde/stat253_coursenotes
  repo-actions: [issue, source]  
  page-footer:
    left: |
      Copyright Kelsey Grinde, CC BY-NC-SA 4.0
  sidebar: 
    collapse-level: 2
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Overview"
      chapters: 
        - schedule.qmd
        - learning-objectives.qmd
        - L01-introductions.qmd
    - part: "Regression: Model Evaluation (Unit 1)"
      chapters:
        - U01-motivation.qmd
        - L02-evaluating-regression-models.qmd
        - L03-overfitting.qmd
        - L04-cross-validation.qmd
    - part: "Regression: Model Selection (Unit 2)"
      chapters: 
        - U02-motivation.qmd
        - L05-model-selection.qmd
        - L06-lasso.qmd
    - part: "Regression: Flexible Models (Unit 3)"
      chapters: 
        - U03-motivation.qmd
        - L07-nonparametric.qmd
        - L08-knn-bias-variance.qmd
        - L09-loess-gams.qmd
        - L10-review.qmd
    - part: "Classification: Modeling Building (Unit 4)"
      chapters: 
        - U04-motivation.qmd
        - L11-logistic-regression.qmd
        - L12-evaluating-classification-models.qmd
    - part: "Classification: Building Flexible Models (Unit 5)"
      chapters: 
        - L13-knn-trees.qmd
        - L14-knn-trees-2.qmd
        - L15-forests.qmd
        - L16-review.qmd
  appendices:
    - r_rstudio.qmd
    - r_resources.qmd
    - stat155.qmd

format:
  html:
    theme:
      light: [sandstone, smaller_lists.scss]
      dark: [superhero, smaller_lists.scss]
    mainfont: ubuntu, sans-serif
    execute:
      echo: true
      code-fold: true
      cache: true
