date-fromat: iso
date: "last-modified"
author: "Dr. Kelsey Grinde"
institute: "Macalester College"

execute:
  warning: false
  cache: true
  freeze: auto

profile:
  default: slides
  group:
  - [slides, book]
