project:
  output-dir: slides
  render: 
    - "L*.qmd"

format: 
  revealjs:
    theme: slides.scss
    multiplex: true
    transition: fade
    chalkboard: true
    auto-stretch: false
    scrollable: true
    footer: <https://kegrinde.github.io/stat253_coursenotes>
